---
title: "Wildlife Forensics Service"
---

The Janecka lab has extensive experience with population genetics and genomics. Dr. Janecka pioneered snow leopard noninvasive analysis and published the first study on phylogeography of this species, and the first annotation and functional assembly of horse Y chromosome. Dr. Janecka has published over 50 manuscripts in books and journals including highly repspected publications such as *Science*, *Nature Communications*, and *Curreny Biology*. Leveraging his 19 years of experience with DNA analysis, microsatellite genotyping, and sequencing his lab has established a program to make wildlife forensics testing available in western Pennsylvania. Currently, the service offered by the Janecka Genomics Lab includes:

- __Species Identification:__ Identification of unknown biological material
- __Individual Identification:__ Identification of individuals and matching samples
- __Sex Identification:__ Determination of sex of an unknown sample
- __Minimumm Number:__ Minimum number of individuals in a mixed sampled
- __Expert Testimony:__ Expert witness testimony in court

If you are interested in submitting a samples please fill out the sample submission form and contact Dr. Janecka or Malenie Quain to arrange a sample drop off. Sample can also be shipped to our address. 


**Processing time**

For standard analysis you will recieve results within 1 month. 
If there is ever a time when we are not able to meet this commitment we will post information and an explanation immediately. 

##Costs
Species Identification: $
Individual Identification: $
Minimum number: $
Sex identification: $



If you submit more than 10 samples there will be a 10% discount on all services



We only offer this service for white-tailed deer at this time. We are expanding the kinds of analysis so please check back in the near future or contact Dr. Janecka.
